import type { Work } from '@/types';

export const WORKS: Work[] = [
  {
    slug: 'gaze-of-others',
    title: '타인의 시선',
    titleEn: 'The Gaze of Others',
    question: '기계는 나를 어떻게 보는가',
    medium: 'AI 컴퓨터비전 · 실시간 얼굴 인식 · 프로젝션',
    year: 2025,
    description: [
      'AI가 관람자의 얼굴을 실시간으로 읽고, 그 위에 살아있는 마스크를 생성한다. 얼굴이 곧 캔버스가 되는 순간.',
      '관람자가 카메라 앞에 서는 순간, AI는 얼굴의 윤곽과 표정을 분석하여 고유한 시각적 레이어를 실시간으로 덧입힌다. 같은 사람이라도 표정이 바뀌면 전혀 다른 작품이 된다.',
      '이 작품은 \'보는 행위\'의 방향을 뒤집는다. 관객이 작품을 바라보는 것이 아니라, 기계가 관객을 바라보고 해석하는 것이다.',
    ],
    spaceCategory: 'exhibition',
    technologies: ['computer-vision', 'projection'],
    specs: {
      minArea: '20m²',
      idealArea: '30–50m²',
      ceilingHeight: '3m+',
      equipment: ['고해상도 프로젝터', 'RGB 카메라', '전용 PC'],
      setupTime: '2–3일',
      power: '220V, 15A 전용 회로',
      darkRoom: true,
    },
    featured: true,
    thumbnail: '/images/works/gaze-of-others-thumb.png',
    heroImage: '/images/works/gaze-of-others-hero.png',
  },
  {
    slug: 'resonance',
    title: '공명',
    titleEn: 'Resonance',
    question: '관계는 어떤 소리를 가지는가',
    medium: 'AI 관계 인식 · 실시간 사운드 생성 · 물리적 오브제',
    year: 2025,
    description: [
      '두 사람이 함께 서면 AI가 그 관계를 읽고 고유한 소리를 생성한다. 관계마다 완전히 다른 음향 경험.',
      'AI는 두 관람자 사이의 거리, 시선의 방향, 몸짓의 동기화 정도를 분석한다. 가까이 서면 조화로운 화음이, 멀어지면 불협화음이 공간을 채운다.',
      '물리적 오브제가 소리에 반응하여 진동하고, 관계의 소리가 눈에 보이는 형태로 변환된다.',
    ],
    spaceCategory: 'exhibition',
    technologies: ['computer-vision', 'sound-generation'],
    specs: {
      minArea: '25m²',
      idealArea: '40–60m²',
      ceilingHeight: '2.7m+',
      equipment: ['깊이 센서 카메라', '멀티채널 스피커 시스템', '물리적 오브제', '전용 PC'],
      setupTime: '3–4일',
      power: '220V, 20A 전용 회로',
      darkRoom: false,
    },
    featured: true,
    thumbnail: '/images/works/resonance-thumb.png',
    heroImage: '/images/works/resonance-hero.png',
  },
  {
    slug: 'afterimage',
    title: '잔상',
    titleEn: 'Afterimage',
    question: '한 번의 관람이 한 번뿐인 작품이 된다',
    medium: 'AI 움직임 트래킹 · 잔상 시각화 · 실시간 렌더링',
    year: 2025,
    description: [
      '관람자의 움직임 잔상을 AI가 트래킹하고 시각화한다. 한 번의 관람이 한 번뿐인 작품이 된다.',
      '공간을 걷는 모든 동선이 빛의 궤적으로 남는다. AI는 움직임의 속도, 방향, 멈춤을 분석하여 각각 다른 색감과 밀도의 잔상을 생성한다.',
      '관람이 끝나면 그 사람만의 유일한 궤적이 작품으로 남고, 다음 관람자가 들어서면 이전의 흔적 위에 새로운 층이 쌓인다.',
    ],
    spaceCategory: 'festival',
    technologies: ['motion-sensing', 'projection', 'generative-ai'],
    specs: {
      minArea: '30m²',
      idealArea: '50–100m²',
      ceilingHeight: '3m+',
      equipment: ['LiDAR 센서', '대형 프로젝터 2대', '전용 PC'],
      setupTime: '2–3일',
      power: '220V, 20A 전용 회로',
      darkRoom: true,
    },
    featured: true,
    thumbnail: '/images/works/afterimage-thumb.png',
    heroImage: '/images/works/afterimage-hero.png',
  },
  {
    slug: 'impossible-companions',
    title: '반려 불가능한 것들',
    titleEn: 'Impossible Companions',
    question: '돌볼 수 없는 것을 돌본다는 것',
    medium: 'AI 인터랙션 · 반려 오브제 · 감각 피드백',
    year: 2025,
    description: [
      'AI가 반려의 불가능성을 시각화한다. 돌볼 수 없는 것에 대한 질문을 던지는 작품.',
      '관람자 앞에 놓인 오브제는 살아있는 듯 반응하지만, 결코 완전히 돌볼 수 없는 존재다. AI는 관람자의 접근 방식을 학습하며, 돌봄의 한계를 감각적으로 드러낸다.',
      '이 작품은 인간이 가진 돌봄의 본능과 그 불가능성 사이의 간극을 탐구한다.',
    ],
    spaceCategory: 'commercial',
    technologies: ['computer-vision', 'generative-ai'],
    specs: {
      minArea: '10m²',
      idealArea: '15–25m²',
      ceilingHeight: '2.4m+',
      equipment: ['커스텀 오브제', '센서 모듈', '소형 디스플레이', '전용 PC'],
      setupTime: '1–2일',
      power: '220V, 10A',
      darkRoom: false,
    },
    featured: false,
    thumbnail: '/images/works/impossible-companions-thumb.png',
    heroImage: '/images/works/impossible-companions-hero.png',
  },
  {
    slug: 'time-of-plants',
    title: '식물의 시간',
    titleEn: 'Time of Plants',
    question: '식물은 우리를 어떻게 느끼는가',
    medium: '식물 전기신호 센싱 · AI 해석 · 빛/소리 변환',
    year: 2025,
    description: [
      '식물의 전기신호를 AI가 해석하여 인간-식물 관계를 빛과 소리로 전환한다.',
      '살아있는 식물에 부착된 센서가 미세한 전기신호를 포착하고, AI가 이를 실시간으로 해석한다. 관람자가 다가가면 식물의 신호가 변하고, 그 변화가 빛과 소리로 번역된다.',
      '인간의 시간과 전혀 다른 속도로 살아가는 식물의 세계를 감각할 수 있게 만드는 작품이다.',
    ],
    spaceCategory: 'commercial',
    technologies: ['bio-sensing', 'sound-generation', 'generative-ai'],
    specs: {
      minArea: '15m²',
      idealArea: '20–40m²',
      ceilingHeight: '2.4m+',
      equipment: ['생체전기 센서 모듈', '식물 관리 시스템', 'LED 조명 시스템', '스피커', '전용 PC'],
      setupTime: '2–3일',
      power: '220V, 10A',
      darkRoom: false,
    },
    featured: false,
    thumbnail: '/images/works/time-of-plants-thumb.png',
    heroImage: '/images/works/time-of-plants-hero.png',
  },
];

export const SPACE_CATEGORIES = [
  { value: 'exhibition', label: '전시관', labelEn: 'Exhibition' },
  { value: 'festival', label: '축제·팝업', labelEn: 'Festival' },
  { value: 'commercial', label: '상업공간', labelEn: 'Commercial' },
] as const;

export const TECHNOLOGIES = [
  { value: 'computer-vision', label: '컴퓨터 비전', labelEn: 'Computer Vision' },
  { value: 'generative-ai', label: '생성형 AI', labelEn: 'Generative AI' },
  { value: 'motion-sensing', label: '모션 센싱', labelEn: 'Motion Sensing' },
  { value: 'projection', label: '프로젝션', labelEn: 'Projection' },
  { value: 'sound-generation', label: '사운드 생성', labelEn: 'Sound Generation' },
  { value: 'bio-sensing', label: '바이오 센싱', labelEn: 'Bio Sensing' },
] as const;
